name = "Halh Mongolian"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Halh Mongolian spellchecker"
khk = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Halh Mongolian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
khk = "TRANSLATE: A spellchecker for Halh Mongolian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.khk"

[windows]
system_product_code = "{EB114361-CBF6-4494-883B-C8A3CBDFD19A}_is1"
legacy_product_codes = [
    { value = "27AEFA51-FC27-4B5F-B060-0BF96A6BA48A", kind = "nsis" },
    { value = "4C40666E-B53A-4197-8750-E34197B49748", kind = "nsis" }
]
