template = "https://github.com/giellalt/template-lang-und"
rev_id = 167
template_sha = "4e541d9adc1d60ff89f947acabb41520c993c85f"

[replacements]
__REPO__ = "lang-khk"
__UND2C__ = "khk"
__UNDEFINED__ = "Halh Mongolian"
__UND__ = "khk"
