template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "halh1238"
__REPO__ = "lang-khk"
__UND2C__ = "khk"
__UNDEFINED__ = "Halh Mongolian"
__UND__ = "khk"
